import { useEffect, useState } from "react";

const API_URL =
  "https://enterprise-ai-multi-cloud-orchestrator.onrender.com";

function Reports() {
  const [resources, setResources] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch(`${API_URL}/api/resources`)
      .then((response) => response.json())
      .then((data) => {
        setResources(data.resources || []);
        setLoading(false);
      })
      .catch((error) => {
        console.error("Report data error:", error);
        setLoading(false);
      });
  }, []);

  const totalResources = resources.length;

  const runningResources = resources.filter(
    (resource) =>
      resource.status === "Running" ||
      resource.status === "Active"
  ).length;

  const cloudProviders = new Set(
    resources.map((resource) => resource.provider)
  ).size;

  const totalCost = resources.reduce((sum, resource) => {
    const cost = parseFloat(
      String(resource.cost || "0").replace("$", "")
    );

    return sum + cost;
  }, 0);

  const generateReport = () => {
    const report = `
ENTERPRISE AI MULTI-CLOUD ORCHESTRATOR
Infrastructure Report

Total Resources: ${totalResources}
Active/Running Resources: ${runningResources}
Cloud Providers: ${cloudProviders}
Estimated Monthly Cost: $${totalCost.toFixed(2)}

Generated by Enterprise AI Multi-Cloud Orchestrator
`;

    const blob = new Blob([report], {
      type: "text/plain"
    });

    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");
    link.href = url;
    link.download = "multi-cloud-infrastructure-report.txt";

    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    URL.revokeObjectURL(url);
  };

  return (
    <div className="reports-page">

      <div className="reports-header">
        <div>
          <h1>Reports</h1>
          <p>
            Generate and review multi-cloud infrastructure reports.
          </p>
        </div>

        <button
          className="generate-report-btn"
          onClick={generateReport}
        >
          Generate Report
        </button>
      </div>

      {loading ? (
        <div className="reports-loading">
          Loading report data...
        </div>
      ) : (
        <>
          <div className="report-summary">

            <div className="report-card">
              <div className="report-icon">▣</div>
              <div>
                <span>Total Resources</span>
                <h2>{totalResources}</h2>
              </div>
            </div>

            <div className="report-card">
              <div className="report-icon">✓</div>
              <div>
                <span>Active Resources</span>
                <h2>{runningResources}</h2>
              </div>
            </div>

            <div className="report-card">
              <div className="report-icon">☁</div>
              <div>
                <span>Cloud Providers</span>
                <h2>{cloudProviders}</h2>
              </div>
            </div>

            <div className="report-card">
              <div className="report-icon">$</div>
              <div>
                <span>Estimated Monthly Cost</span>
                <h2>${totalCost.toFixed(2)}</h2>
              </div>
            </div>

          </div>

          <div className="report-section">

            <div className="section-title">
              <h2>Infrastructure Report</h2>
              <span>Live API Data</span>
            </div>

            <div className="report-table-container">

              <table className="report-table">

                <thead>
                  <tr>
                    <th>Resource</th>
                    <th>Provider</th>
                    <th>Type</th>
                    <th>Status</th>
                    <th>Region</th>
                    <th>Cost</th>
                  </tr>
                </thead>

                <tbody>

                  {resources.map((resource) => (
                    <tr key={resource.id}>

                      <td>
                        <strong>
                          {resource.name}
                        </strong>
                      </td>

                      <td>
                        {resource.provider}
                      </td>

                      <td>
                        {resource.type}
                      </td>

                      <td>
                        <span
                          className={
                            resource.status === "Running" ||
                            resource.status === "Active"
                              ? "status-active"
                              : "status-warning"
                          }
                        >
                          {resource.status}
                        </span>
                      </td>

                      <td>
                        {resource.region}
                      </td>

                      <td>
                        {resource.cost || "N/A"}
                      </td>

                    </tr>
                  ))}

                </tbody>

              </table>

              {resources.length === 0 && (
                <div className="empty-report">
                  No infrastructure resources found.
                </div>
              )}

            </div>

          </div>

          <div className="report-section">

            <div className="section-title">
              <h2>AI Generated Summary</h2>
              <span>Intelligent Analysis</span>
            </div>

            <div className="ai-report-box">

              <div className="ai-report-icon">
                ✦
              </div>

              <div>
                <h3>
                  Multi-Cloud Infrastructure Overview
                </h3>

                <p>
                  The orchestrator is currently managing{" "}
                  <strong>{totalResources}</strong>{" "}
                  cloud resources across{" "}
                  <strong>{cloudProviders}</strong>{" "}
                  cloud providers.
                </p>

                <p>
                  {runningResources} resources are currently
                  active or running. The estimated combined
                  monthly infrastructure cost is{" "}
                  <strong>
                    ${totalCost.toFixed(2)}
                  </strong>.
                </p>

                <p>
                  AI-powered optimization can be used to
                  identify unnecessary resources, reduce
                  cloud costs, and improve multi-cloud
                  resource utilization.
                </p>
              </div>

            </div>

          </div>

        </>
      )}

      <style>{`

        .reports-page {
          padding: 30px;
          color: #172033;
        }

        .reports-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 30px;
          gap: 20px;
        }

        .reports-header h1 {
          margin: 0 0 8px;
          font-size: 30px;
        }

        .reports-header p {
          margin: 0;
          color: #6b7280;
        }

        .generate-report-btn {
          border: none;
          padding: 12px 20px;
          border-radius: 10px;
          background: #111827;
          color: white;
          cursor: pointer;
          font-size: 14px;
          font-weight: 600;
        }

        .generate-report-btn:hover {
          opacity: 0.9;
        }

        .reports-loading {
          padding: 50px;
          text-align: center;
          color: #6b7280;
        }

        .report-summary {
          display: grid;
          grid-template-columns:
            repeat(4, minmax(0, 1fr));
          gap: 18px;
          margin-bottom: 25px;
        }

        .report-card {
          background: white;
          border: 1px solid #e5e7eb;
          border-radius: 14px;
          padding: 20px;
          display: flex;
          align-items: center;
          gap: 15px;
        }

        .report-icon {
          width: 45px;
          height: 45px;
          border-radius: 10px;
          background: #f3f4f6;
          display: flex;
          align-items: center;
          justify-content: center;
          font-size: 20px;
          font-weight: 700;
        }

        .report-card span {
          display: block;
          color: #6b7280;
          font-size: 13px;
          margin-bottom: 5px;
        }

        .report-card h2 {
          margin: 0;
          font-size: 23px;
        }

        .report-section {
          background: white;
          border: 1px solid #e5e7eb;
          border-radius: 14px;
          padding: 24px;
          margin-bottom: 25px;
        }

        .section-title {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 20px;
        }

        .section-title h2 {
          margin: 0;
          font-size: 20px;
        }

        .section-title span {
          font-size: 12px;
          color: #6b7280;
          background: #f3f4f6;
          padding: 6px 10px;
          border-radius: 20px;
        }

        .report-table-container {
          overflow-x: auto;
        }

        .report-table {
          width: 100%;
          border-collapse: collapse;
          min-width: 750px;
        }

        .report-table th {
          text-align: left;
          padding: 14px;
          background: #f9fafb;
          color: #6b7280;
          font-size: 12px;
          font-weight: 600;
        }

        .report-table td {
          padding: 15px 14px;
          border-top: 1px solid #f0f0f0;
          font-size: 13px;
        }

        .status-active {
          display: inline-block;
          padding: 5px 9px;
          border-radius: 20px;
          background: #ecfdf5;
          color: #047857;
          font-size: 11px;
          font-weight: 600;
        }

        .status-warning {
          display: inline-block;
          padding: 5px 9px;
          border-radius: 20px;
          background: #fff7ed;
          color: #c2410c;
          font-size: 11px;
          font-weight: 600;
        }

        .empty-report {
          padding: 30px;
          text-align: center;
          color: #6b7280;
        }

        .ai-report-box {
          display: flex;
          gap: 18px;
          padding: 22px;
          border-radius: 12px;
          background: #f8fafc;
          border: 1px solid #e5e7eb;
        }

        .ai-report-icon {
          width: 45px;
          height: 45px;
          min-width: 45px;
          border-radius: 10px;
          display: flex;
          align-items: center;
          justify-content: center;
          background: #111827;
          color: white;
          font-size: 20px;
        }

        .ai-report-box h3 {
          margin: 0 0 10px;
        }

        .ai-report-box p {
          margin: 8px 0;
          color: #4b5563;
          line-height: 1.6;
          font-size: 14px;
        }

        @media (max-width: 1000px) {

          .report-summary {
            grid-template-columns:
              repeat(2, minmax(0, 1fr));
          }

        }

        @media (max-width: 650px) {

          .reports-page {
            padding: 18px;
          }

          .reports-header {
            flex-direction: column;
            align-items: flex-start;
          }

          .report-summary {
            grid-template-columns: 1fr;
          }

          .report-section {
            padding: 18px;
          }

          .section-title {
            align-items: flex-start;
            gap: 10px;
            flex-direction: column;
          }

        }

      `}</style>

    </div>
  );
}

export default Reports;